Revert "sse4 regular quantize"
This reverts commit 0d3ed089f1f0a00b7729161db8680ac1f0ff3402.

Appears to breaks borg build on non sse4 machines.

Eg.
In file included from third_party/libvpx/git_root/vp8/encoder/x86/quantize_sse4.c:12:
third_party/crosstool/v17/stable/clang/bin/../lib/clang/google3-trunk/include/smmintrin.h:28:2: error: "SSE4.1 instruction set not enabled"
#error "SSE4.1 instruction set not enabled"
 ^
third_party/libvpx/git_root/vp8/encoder/x86/quantize_sse4.c:36:5: error: use of undeclared identifier '__m128i'
    __m128i sz0, x0, sz1, x1, y0, y1, x_minus_zbin0, x_minus_zbin1,

Change-Id: Ic684e8b6e38c51d166848adea8554be35be9ed50