Update patch set 2
Patch Set 2:

Does not compile (rememember --enable-experimental --enable-clpf).  May be related to:
commit e6b129446bfc1c1ddaef435adda6742cddd80a12
Author: Michael Bebenita <mbebenita@mozilla.com>
Date:   Thu Aug 25 14:40:54 2016 -0700

    Bit accounting.
    
    This patch adds bit account infrastructure to the bit reader API.
    When configured with --enable-accounting, every bit reader API
    function records the number of bits necessary to decoding a symbol.
    Accounting symbol entries are collected in global accounting data
    structure, that can be used to understand exactly where bits are
    spent (http://aomanalyzer.org). The data structure is cleared and
    reused each frame to reduce memory usage. When configured without
    --enable-accounting, bit accounting does not incur any runtime
    overhead.
    
    All aom_read_xxx functions now have an additional string parameter
    that specifies the symbol name. By default, the ACCT_STR macro is
    used (which expands to __func__). For more precise accounting,
    these should be replaced with more descriptive names.
    
    Change-Id: Ia2e1343cb842c9391b12b77272587dfbe307a56d

Errors:

av1/decoder/decodeframe.c: In function ‘decode_partition’:
av1/decoder/decodeframe.c:1800:52: error: ‘ACCT_STR’ undeclared (first use in this function)
       cm->clpf_blocks[tl] = aom_read_literal(r, 1, ACCT_STR);
                                                    ^
av1/decoder/decodeframe.c:1800:52: note: each undeclared identifier is reported only once for each function it appears in
av1/decoder/decodeframe.c:1800:7: error: too many arguments to function ‘aom_read_literal’
       cm->clpf_blocks[tl] = aom_read_literal(r, 1, ACCT_STR);
       ^
In file included from av1/decoder/decodeframe.c:22:0:
./aom_dsp/bitreader.h:85:19: note: declared here
 static INLINE int aom_read_literal(aom_reader *r, int bits) {
                   ^
av1/decoder/decodeframe.c:1803:7: error: too many arguments to function ‘aom_read_literal’
       cm->clpf_blocks[tl] = aom_read_literal(r, 1, ACCT_STR);
       ^
In file included from av1/decoder/decodeframe.c:22:0:
./aom_dsp/bitreader.h:85:19: note: declared here
 static INLINE int aom_read_literal(aom_reader *r, int bits) {
                   ^
av1/decoder/decodeframe.c:1812:9: error: too many arguments to function ‘aom_read_literal’
         cm->clpf_blocks[tl] = aom_read_literal(r, 1, ACCT_STR);
         ^
In file included from av1/decoder/decodeframe.c:22:0:
./aom_dsp/bitreader.h:85:19: note: declared here
 static INLINE int aom_read_literal(aom_reader *r, int bits) {
                   ^
av1/decoder/decodeframe.c:1816:9: error: too many arguments to function ‘aom_read_literal’
         cm->clpf_blocks[tr] = aom_read_literal(r, 1, ACCT_STR);
         ^
In file included from av1/decoder/decodeframe.c:22:0:
./aom_dsp/bitreader.h:85:19: note: declared here
 static INLINE int aom_read_literal(aom_reader *r, int bits) {
                   ^
av1/decoder/decodeframe.c:1820:9: error: too many arguments to function ‘aom_read_literal’
         cm->clpf_blocks[bl] = aom_read_literal(r, 1, ACCT_STR);
         ^
In file included from av1/decoder/decodeframe.c:22:0:
./aom_dsp/bitreader.h:85:19: note: declared here
 static INLINE int aom_read_literal(aom_reader *r, int bits) {
                   ^
av1/decoder/decodeframe.c:1824:9: error: too many arguments to function ‘aom_read_literal’
         cm->clpf_blocks[br] = aom_read_literal(r, 1, ACCT_STR);
         ^
In file included from av1/decoder/decodeframe.c:22:0:
./aom_dsp/bitreader.h:85:19: note: declared here
 static INLINE int aom_read_literal(aom_reader *r, int bits) {
                   ^
make[1]: *** [av1/decoder/decodeframe.c.o] Error 1
make: *** [.DEFAULT] Error 2

Patch-set: 2