Update patch set 2
Patch Set 2:

> Change has been successfully merged by Yi Luo

Merge conflict happens (HBD baseline), please fix it.

C++ compilation of rule '//third_party/libvpx:vp10_sse4_asm' failed (Exit 1) [forge_remote_host=ixay126].
third_party/libvpx/git_root/vp10/common/x86/vp10_highbd_convolve_sse4.c:228:3: error: unknown type name 'HbdSubpelFilterCoeffs'; did you mean 'SubpelFilterCoeffs'?

Patch-set: 2