Revert "vp8: Add temporal denoising for UV-channel."
This reverts commit 94ae0430d28c7204af0ee911e90e598542c65fdc.

Causes compiler errors and warnings in VS2008.

2>denoising_sse2.c
2>..\..\vp8\encoder\x86\denoising_sse2.c(21) : error C2054: expected '(' to follow 'inline'
2>..\..\vp8\encoder\x86\denoising_sse2.c(21) : error C2085: 'abs_sum_diff_16x1' : not in formal parameter list
2>..\..\vp8\encoder\x86\denoising_sse2.c(21) : error C2143: syntax error : missing ';' before '{'
2>..\..\vp8\encoder\x86\denoising_sse2.c(119) : warning C4013: 'abs_sum_diff_16x1' undefined; assuming extern returning int
2>..\..\vp8\encoder\x86\denoising_sse2.c(122) : warning C4018: '>' : signed/unsigned mismatch
2>..\..\vp8\encoder\x86\denoising_sse2.c(173) : warning C4018: '>' : signed/unsigned mismatch
2>..\..\vp8\encoder\x86\denoising_sse2.c(303) : warning C4018: '>' : signed/unsigned mismatch
2>..\..\vp8\encoder\x86\denoising_sse2.c(368) : warning C4018: '>' : signed/unsigned mismatch

Change-Id: I4a80b9cd1316c0e9dd9d93a3d1038b3657669d9c