Revert "Fix building with iOS 9 beta SDK" [regression]
This reverts commit 78637b61361ab11425afd4a67d43c4df948647a6.

Didn't quite properly disable the armv6 media instruction assembly; while it removed them from the build, the symbols are still being used somewhere and the resulting library can fail to link into a final executable:

Undefined symbols for architecture armv7:
  "_vp8_sixtap_predict4x4_armv6", referenced from:
      _vp8_decode_frame in VPX(decodeframe.c.o)
  "_vp8_bilinear_predict4x4_armv6", referenced from:
      _vp8_decode_frame in VPX(decodeframe.c.o)
  "_vp8_intra4x4_predict_armv6", referenced from:
      _mt_decode_mb_rows in VPX(threading.c.o)
      _vp8_decode_frame in VPX(decodeframe.c.o)
ld: symbol(s) not found for architecture armv7

Change-Id: Ie8c2441eed73d4ab6a86281fd56f9309ba1a65a3