Declare the operator== overload for M128A in the global namespace.
ADL will look this up from the callsite namespace iff it is declared before the
callsite or from teh parent namespace of the class type (the global namespace).

This patch has been tested on MSVS 2015 and clang-3.8.

Without this patch clang reports:
In file included from ../libvpx/test/avg_test.cc:15:
../libvpx\third_party/googletest/src/include/gtest/gtest.h:18861:16: error:
call to function 'operator==' that is neither visible in the template
definition nor found by argument-dependent lookup
  if (expected == actual) {
               ^
../libvpx\third_party/googletest/src/include/gtest/gtest.h:18897:12: note: in
instantiation of function template specialization
'testing::internal::CmpHelperEQ<_M128A, _M128A>' requested here
    return CmpHelperEQ(expected_expression, actual_expression, expected,
           ^
../libvpx\test/register_state_check.h:78:7: note: in instantiation of function
template specialization
'testing::internal::EqHelper<false>::Compare<_M128A, _M128A>' requested here
      EXPECT_EQ(*xmm_pre, *xmm_post) << "xmm" << i << " has been modified!";
      ^
../libvpx\third_party/googletest/src/include/gtest/gtest.h:19749:67: note:
expanded from macro 'EXPECT_EQ'
                      EqHelper<GTEST_IS_NULL_LITERAL_(expected)>::Compare, \
                                                                  ^
../libvpx\test/register_state_check.h:42:13: note: 'operator==' should be
declared prior to the call site or in the global namespace
inline bool operator==(const M128A& lhs, const M128A& rhs) {
            ^

Change-Id: I00ba74712c9b617b9d81761abed1e14d8f25d8e3