Update patch set 2
Patch Set 2:

This patch broke the runborgs tool. Error message:

9,801 / 16,803] Compiling third_party/icu/source/common/servslkf.cpp [for host]
____From Compiling third_party/ffmpeg/v44799/libavcodec/libvpxenc.c:
third_party/ffmpeg/v44799/libavcodec/libvpxenc.c:109:6: error: use of undeclared identifier 'VP8E_UPD_ENTROPY'
    [VP8E_UPD_ENTROPY]           = "VP8E_UPD_ENTROPY",
     ^
third_party/ffmpeg/v44799/libavcodec/libvpxenc.c:110:6: error: use of undeclared identifier 'VP8E_UPD_REFERENCE'
    [VP8E_UPD_REFERENCE]         = "VP8E_UPD_REFERENCE",
     ^
third_party/ffmpeg/v44799/libavcodec/libvpxenc.c:111:6: error: use of undeclared identifier 'VP8E_USE_REFERENCE'; did you mean 'VP8_SET_REFERENCE'?
    [VP8E_USE_REFERENCE]         = "VP8E_USE_REFERENCE",
     ^~~~~~~~~~~~~~~~~~
     VP8_SET_REFERENCE
third_party/libvpx/git_root/vpx/./vp8.h:45:3: note: 'VP8_SET_REFERENCE' declared here
  VP8_SET_REFERENCE           = 1,    /**< pass in an external frame into decoder to be used as reference frame */
  ^
3 errors generated.
ERROR: /tmp/tmp.JWooRfUtEL/READONLY/google3/tools/build_defs/python/pytype.bzl:52:3: C++ compilation of rule '//third_party/ffmpeg/v44799:libavcodec' failed (Exit 1) [forge_remote_host=ixw63].
____Building complete.
____Elapsed time: 64.432s, Forge stats: 6364/6398 actions cached, 8.0s CPU used, 0.0s queue time, 0.0 MB ObjFS output, 0.0 MB local output, Critical Path: 8.32s, Forge (94.38% of the time): [parse: 92.49%, queue: 0.00%, setup: 0.00%, process: 0.00%]
____Still uploading to http://sponge/f1385c53-cb99-4ef1-8256-96380913d43f

Patch-set: 2
Reviewer: Gerrit User 1003005 <1003005@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=0