Revert "VP8 for ARMv8 by using NEON intrinsics 10"
This reverts commit c500fc22c1bb2a3ae5c318bfb806f7e9bd57ce25

There is an issue with gcc 4.6 in the Android NDK:
loopfiltersimpleverticaledge_neon.c: In function 'vp8_loop_filter_bvs_neon':
loopfiltersimpleverticaledge_neon.c:176:1: error: insn does not satisfy its constraints:

Change-Id: I95b6509d12f075890308914cc691b813d2e5cd9f