Update patch set 7
Patch Set 7:

Tested the patch on Windows.
Configuration:
$ ../libvpx/configure --target=x86_64-win64-vs11

And got the following errors:

Warning	1	warning C4013: '_mm_broadcastsi128_si256' undefined; assuming extern returning int	C:\webm\libvpx\vp9\common\x86\vp9_subpixel_8t_intrin_avx2.c	53	1	vpx
Error	2	error C2440: '=' : cannot convert from 'int' to '__m256i'	C:\webm\libvpx\vp9\common\x86\vp9_subpixel_8t_intrin_avx2.c	53	1	vpx
Error	3	error C2440: '=' : cannot convert from 'int' to '__m256i'	C:\webm\libvpx\vp9\common\x86\vp9_subpixel_8t_intrin_avx2.c	305	1	vpx
Error	4	error LNK1104: cannot open file 'vpxmdd.lib'	C:\webm\intel32\LINK	vpxdec
	5	IntelliSense: identifier "_mm_broadcastsi128_si256" is undefined	c:\webm\libvpx\vp9\common\x86\vp9_subpixel_8t_intrin_avx2.c	53	20	vpx
	6	IntelliSense: identifier "_mm_broadcastsi128_si256" is undefined	c:\webm\libvpx\vp9\common\x86\vp9_subpixel_8t_intrin_avx2.c	305	20	vpx

Patch-set: 7
Label: Code-Review=0
Label: Commit-Queue=0
Label: Verified=0