Use the correct member for initialization
On Windows this fails with:
error C2440: '=': cannot convert from int_mv to uint32_t

Change-Id: I51630efd0e83a0ce620c91aa7859dd6fc1572e99