Revert "Cleaning up vp9_append_sub8x8_mvs_for_idx."
This reverts commit 52fa10a9a337dcaf2b30839560841ec836a94717.

Compiler casting errors in Visual Studio.
..\..\vp9\common\vp9_findnearmv.c(66) : error C2440: 'initializing' : cannot convert from 'int_mv' to 'uint32_t'

Change-Id: I94a7fa12d79116a85c25037ee831b809062d866b