MSVS compiler error
Visual Studio reports and error on the line
  static const int bsize2 = bsize >> 1;

"error C2099: initializer is not a constant"
even though bsize is defined as a const int

Change-Id: I76cb06f736bd9c90107a26bfb3c130ec3f6c33de