Update patch set 1
Patch Set 1:

Is there anything special I need to do to get it to build? My NDK gives this when ssse3 is enabled:
In file included from libvpx/test/android/../../../libvpx/vp9/common/x86/vp9_subpixel_8t_intrin_ssse3.c:11:0:
/usr/local/google/home/johannkoenig/android-ndk-r9d/toolchains/x86-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/i686-linux-android/4.6/include/tmmintrin.h:31:3: error: #error "SSSE3 instruction set not enabled"

ssse3 also brings asm_offsets requirements, but I'm hoping to get rid of that soon. This needs to land and get some testing:
https://gerrit.chromium.org/gerrit/#/c/47281/

Patch-set: 1
Reviewer: Gerrit User 1117029 <1117029@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0
Label: Verified=0