Update patch set 1
Patch Set 1:

Weird build failure which is not related to this commit:

vp9/common/vp9_loopfilter.c: In function 'build_lfi':
vp9/common/vp9_loopfilter.c:550:19: error: initialization makes integer from pointer without a cast [-Werror]
cc1: all warnings being treated as errors
make[1]: *** [vp9/common/vp9_loopfilter.c.o] Error 1

Patch-set: 1
Reviewer: Gerrit User 1002442 <1002442@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=0
Label: Commit-Queue=0
Label: Verified=0